# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrizone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nutrientfoodname', to='nutrizone.Food'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measure',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrientname', to='nutrizone.Nutrient'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodname', to='nutrizone.Food'),
        ),
    ]
