# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrizone', '0003_food_dbnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='dbnumber',
            new_name='ndbno',
        ),
    ]
