# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrizone', '0003_remove_measure_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='brname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='specialmeasure',
            field=models.CharField(default='', max_length=100),
        ),
    ]
