# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrizone', '0004_auto_20170621_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrients',
            name='unit',
            field=models.CharField(default='g', max_length=10),
            preserve_default=False,
        ),
    ]
