# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrizone', '0005_auto_20170803_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrizone.Food')),
            ],
        ),
        migrations.CreateModel(
            name='UserMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='userMeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermeal', to='nutrizone.UserMeal'),
        ),
    ]
