# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrizone', '0005_nutrients_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cup_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='value',
            field=models.FloatField(),
        ),
    ]
