# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrizone', '0006_auto_20170814_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealingredient',
            old_name='userMeal',
            new_name='usermeal',
        ),
    ]
